
*****************************************************************************
Oct 18,2016 13:41:30 [info]   Execution Started of Test Class com.primeresponse.testcases.Track.VerifyWidgets_TrackSummary and Test method testVerifyWidgets_TrackSummary
*****************************************************************************
Oct 18,2016 13:41:43 [info]  open application giturl
Oct 18,2016 13:43:59 [info]  log-in into application
Oct 18,2016 13:43:59 [info]  Select Selenium Test Ford Account if not selected
Oct 18,2016 13:45:22 [info]  Go to Track > Summary
Oct 18,2016 13:45:33 [info]  Oct 18,2016 13:45:33 [info]  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Error message >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.primeresponse.pagehelper.TrackHelper.verifyWidgetsTrackSummary(TrackHelper.java:111)
	at com.primeresponse.testcases.Track.VerifyWidgets_TrackSummary.testVerifyWidgets_TrackSummary(VerifyWidgets_TrackSummary.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Oct 18,2016 13:45:33 [info]  End Execution of Test Class com.primeresponse.testcases.Track.VerifyWidgets_TrackSummary
*****************************************************************************

*****************************************************************************
Oct 18,2016 13:47:16 [info]   Execution Started of Test Class com.primeresponse.testcases.Track.Verify_TrackProductReviewFeed and Test method testVerify_TrackProductReviewFeed
*****************************************************************************
Oct 18,2016 13:47:31 [info]  open application giturl
Oct 18,2016 13:49:09 [info]  log-in into application
Oct 18,2016 13:49:09 [info]  Select Selenium Test Account if not selected
Oct 18,2016 13:54:27 [info]  Oct 18,2016 13:54:27 [info]  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Error message >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
java.lang.AssertionError: Element Locator ://div[@id='product_id_chzn']//li Not found expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.primeresponse.util.DriverHelper.getSize(DriverHelper.java:268)
	at com.primeresponse.pagehelper.TrackHelper.verify_TrackProductReviewFeed(TrackHelper.java:868)
	at com.primeresponse.testcases.Track.Verify_TrackProductReviewFeed.testVerify_TrackProductReviewFeed(Verify_TrackProductReviewFeed.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Oct 18,2016 13:54:27 [info]  End Execution of Test Class com.primeresponse.testcases.Track.Verify_TrackProductReviewFeed
*****************************************************************************

*****************************************************************************
Oct 18,2016 14:01:37 [info]   Execution Started of Test Class com.primeresponse.testcases.Track.Verify_TrackCompetitiorsGoToSite and Test method testVerify_TrackCompetitiorsGoToSite
*****************************************************************************
Oct 18,2016 14:01:51 [info]  open application giturl
Oct 18,2016 14:03:09 [info]  log-in into application
Oct 18,2016 14:03:10 [info]  Select Selenium Test Ford Account if not selected
Oct 18,2016 14:03:48 [info]  Oct 18,2016 14:03:48 [info]  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Error message >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.primeresponse.pagehelper.TrackHelper.verify_TrackCompetitiorsGoToSite(TrackHelper.java:498)
	at com.primeresponse.testcases.Track.Verify_TrackCompetitiorsGoToSite.testVerify_TrackCompetitiorsGoToSite(Verify_TrackCompetitiorsGoToSite.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Oct 18,2016 14:03:48 [info]  End Execution of Test Class com.primeresponse.testcases.Track.Verify_TrackCompetitiorsGoToSite
*****************************************************************************

*****************************************************************************
Oct 18,2016 14:08:18 [info]   Execution Started of Test Class com.primeresponse.testcases.Track.Verify_TotalResponsesOnExternalFeedAndSummary and Test method testVerify_TotalResponsesOnExternalFeedAndSummary
*****************************************************************************
Oct 18,2016 14:08:27 [info]  open application giturl
Oct 18,2016 14:09:59 [info]  log-in into application
Oct 18,2016 14:10:00 [info]  Select Selenium Test Ford Account if not selected
Oct 18,2016 14:10:30 [info]  Go to Track > Summary
Oct 18,2016 14:10:46 [info]  Verify total number of ratings on External Feed and Summary page.
Oct 18,2016 14:10:46 [info]  End Execution of Test Class com.primeresponse.testcases.Track.Verify_TotalResponsesOnExternalFeedAndSummary
*****************************************************************************

*****************************************************************************
Oct 18,2016 14:12:46 [info]   Execution Started of Test Class com.primeresponse.testcases.Track.Verify_GoToSite_ExternalFeed and Test method testVerify_GoToSite_ExternalFeed
*****************************************************************************
Oct 18,2016 14:13:17 [info]  open application giturl
Oct 18,2016 14:14:48 [info]  log-in into application
Oct 18,2016 14:14:48 [info]  Select Selenium Test Ford Account if not selected
Oct 18,2016 14:15:00 [info]  Go to Track > External Feed
Oct 18,2016 14:15:36 [info]  Oct 18,2016 14:15:36 [info]  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Error message >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.primeresponse.pagehelper.TrackHelper.verifyGoToSiteExternalFeed(TrackHelper.java:854)
	at com.primeresponse.testcases.Track.Verify_GoToSite_ExternalFeed.testVerify_GoToSite_ExternalFeed(Verify_GoToSite_ExternalFeed.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Oct 18,2016 14:15:36 [info]  End Execution of Test Class com.primeresponse.testcases.Track.Verify_GoToSite_ExternalFeed
*****************************************************************************

*****************************************************************************
Oct 18,2016 14:54:06 [info]   Execution Started of Test Class com.primeresponse.testcases.Track.Verify_FeedsOnSharedExternalFeed and Test method testVerify_FeedsOnSharedExternalFeed
*****************************************************************************
Oct 18,2016 14:54:16 [info]  open application giturl
Oct 18,2016 14:54:46 [info]  log-in into application
Oct 18,2016 14:54:46 [info]  Select Selenium Test Ford Account if not selected
Oct 18,2016 14:55:01 [info]  Go to Track > External Feed
Oct 18,2016 15:00:10 [info]  Oct 18,2016 15:00:10 [info]  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Error message >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
java.lang.AssertionError: Element Locator ://div[@class='table']/table/tbody/tr[13]//a[@data-original-title='Share']/i Not found expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.primeresponse.util.DriverHelper.clickOn(DriverHelper.java:238)
	at com.primeresponse.pagehelper.TrackHelper.fetchFeedsExternalFeed(TrackHelper.java:199)
	at com.primeresponse.testcases.Track.Verify_FeedsOnSharedExternalFeed.testVerify_FeedsOnSharedExternalFeed(Verify_FeedsOnSharedExternalFeed.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Oct 18,2016 15:00:10 [info]  End Execution of Test Class com.primeresponse.testcases.Track.Verify_FeedsOnSharedExternalFeed
*****************************************************************************

*****************************************************************************
Oct 18,2016 15:02:10 [info]   Execution Started of Test Class com.primeresponse.testcases.Track.Verify_ExternalFeedReviewDetails and Test method testVerify_ExternalFeedReviewDetails
*****************************************************************************
Oct 18,2016 15:02:23 [info]  open application giturl
Oct 18,2016 15:02:56 [info]  log-in into application
Oct 18,2016 15:02:56 [info]  Select Selenium Test Ford Account if not selected
Oct 18,2016 15:03:08 [info]  Go to Track > External Feed
Oct 18,2016 15:08:18 [info]  Oct 18,2016 15:08:18 [info]  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Error message >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
java.lang.AssertionError: Element Locator ://tbody[@id='external-feed-reviews']/tr//a[@data-original-title='View More']/i Not found expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.primeresponse.util.DriverHelper.getSize(DriverHelper.java:268)
	at com.primeresponse.pagehelper.TrackHelper.verify_ExternalFeedReviewDetails(TrackHelper.java:883)
	at com.primeresponse.testcases.Track.Verify_ExternalFeedReviewDetails.testVerify_ExternalFeedReviewDetails(Verify_ExternalFeedReviewDetails.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Oct 18,2016 15:08:18 [info]  End Execution of Test Class com.primeresponse.testcases.Track.Verify_ExternalFeedReviewDetails
*****************************************************************************

*****************************************************************************
Oct 18,2016 15:09:54 [info]   Execution Started of Test Class com.primeresponse.testcases.Track.Sort_TrackCompetitiorsRating and Test method testSort_TrackCompetitiorsRating
*****************************************************************************
Oct 18,2016 15:10:03 [info]  open application giturl
Oct 18,2016 15:10:42 [info]  log-in into application
Oct 18,2016 15:10:42 [info]  Select Selenium Test Ford Account if not selected
Oct 18,2016 15:12:57 [info]  Verify sorting functionality of rating column under Track >Competitors latest reviews widget.
Oct 18,2016 15:12:57 [info]  End Execution of Test Class com.primeresponse.testcases.Track.Sort_TrackCompetitiorsRating
*****************************************************************************

*****************************************************************************
Oct 18,2016 15:13:18 [info]   Execution Started of Test Class com.primeresponse.testcases.Track.Sort_TrackCompetitiorsDescriptionCol and Test method testSort_TrackCompetitiorsDescriptionCol
*****************************************************************************
Oct 18,2016 15:13:26 [info]  open application giturl
Oct 18,2016 15:14:12 [info]  log-in into application
Oct 18,2016 15:14:12 [info]  Select Selenium Test Ford Account if not selected
Oct 18,2016 15:16:23 [info]  Verify sorting functionality of Description column under Track >Competitors latest reviews widget.
Oct 18,2016 15:16:23 [info]  End Execution of Test Class com.primeresponse.testcases.Track.Sort_TrackCompetitiorsDescriptionCol
*****************************************************************************

*****************************************************************************
Oct 18,2016 15:18:49 [info]   Execution Started of Test Class com.primeresponse.testcases.Track.Check_ReviewCount and Test method testDelete_ExternalFeed
*****************************************************************************
Oct 18,2016 15:18:58 [info]  open application giturl
Oct 18,2016 15:19:22 [info]  log-in into application
Oct 18,2016 15:19:34 [info]  Go to Track > Summary
Oct 18,2016 15:19:34 [info]  Select 365 days of segmentation if not selected
Oct 18,2016 15:24:45 [info]  Oct 18,2016 15:24:45 [info]  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Error message >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
java.lang.AssertionError: Element Locator ://div[@class='widget']/table/tbody/tr[4]/td[1] Not found expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.primeresponse.util.DriverHelper.getText(DriverHelper.java:305)
	at com.primeresponse.pagehelper.TrackHelper.storeListenersAndReviewCount(TrackHelper.java:98)
	at com.primeresponse.testcases.Track.Check_ReviewCount.testDelete_ExternalFeed(Check_ReviewCount.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Oct 18,2016 15:24:45 [info]  End Execution of Test Class com.primeresponse.testcases.Track.Check_ReviewCount
*****************************************************************************

*****************************************************************************
Oct 18,2016 17:38:40 [info]   Execution Started of Test Class com.primeresponse.testcases.Track.Check_ReviewCount and Test method testDelete_ExternalFeed
*****************************************************************************
Oct 18,2016 17:38:50 [info]  open application giturl
Oct 18,2016 17:41:10 [info]  log-in into application
Oct 18,2016 17:41:32 [info]  Go to Track > Summary
Oct 18,2016 17:41:32 [info]  Select 365 days of segmentation if not selected
Oct 18,2016 17:46:43 [info]  Oct 18,2016 17:46:43 [info]  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Error message >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
java.lang.AssertionError: Element Locator ://div[@class='widget']/table/tbody/tr[4]/td[2] Not found expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.primeresponse.util.DriverHelper.getText(DriverHelper.java:305)
	at com.primeresponse.pagehelper.TrackHelper.storeListenersAndReviewCount(TrackHelper.java:98)
	at com.primeresponse.testcases.Track.Check_ReviewCount.testDelete_ExternalFeed(Check_ReviewCount.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Oct 18,2016 17:46:43 [info]  End Execution of Test Class com.primeresponse.testcases.Track.Check_ReviewCount
*****************************************************************************

*****************************************************************************
Oct 18,2016 17:51:32 [info]   Execution Started of Test Class com.primeresponse.testcases.Track.Check_ReviewCount and Test method testheck_ReviewCount
*****************************************************************************
Oct 18,2016 17:51:42 [info]  open application giturl
Oct 18,2016 17:52:53 [info]  log-in into application
Oct 18,2016 17:53:39 [info]  Go to Track > Summary
Oct 18,2016 17:53:39 [info]  Select 365 days of segmentation if not selected
Oct 18,2016 17:58:49 [info]  Oct 18,2016 17:58:49 [info]  <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<< Error message >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
java.lang.AssertionError: Element Locator ://div[@class='widget']/table/tbody/tr[4]/td[3] Not found expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.primeresponse.util.DriverHelper.getText(DriverHelper.java:305)
	at com.primeresponse.pagehelper.TrackHelper.storeListenersAndReviewCount(TrackHelper.java:100)
	at com.primeresponse.testcases.Track.Check_ReviewCount.testheck_ReviewCount(Check_ReviewCount.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Oct 18,2016 17:58:49 [info]  End Execution of Test Class com.primeresponse.testcases.Track.Check_ReviewCount
*****************************************************************************
